#!/usr/bin/env python3
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
#

#
# Stress client that hammers the server with pipelined requests
#

import socket
import sys

from time import sleep

def main(argv):
    if len(argv) != 3:
        print(f"Usage: {argv[0]} host port")
        return 1

    try:

        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client:
            client.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
            client.setblocking(True)
            while True:
                try:
                    client.connect((argv[1], int(argv[2])))
                    break
                except ConnectionRefusedError:
                    print("Conn refused... retrying")
                    sleep(1)
            while True:
                sleep(100)

    except KeyboardInterrupt:
        print("Done")
        return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))

